### ISSUE TITLE
Privacy Issues

### ISSUE THREAD

**Issue by aksalj** [anyangocynthia/nyumba_kumi#1]
[http://41.242.2.154:3001/users/](http://41.242.2.154:3001/users/) clearly lists information I would not want everyone to have access to. Plus it can be edited :frowning:. In fact, all the API endpoints (documented [here](https://github.com/anyangocynthia/nyumba_kumi/blob/master/README.md)) seem to be open to anyone. Are you planning on fixing that, or was that part of the design?

**Comment by muaad** [comment]
That is not part of the plan, of course. And, we are not even using that page. It is something Rails generated automatically. 

Am actually currently working on a separate branch for refactoring the code, renaming some models, removing things we are not using, multi-tennanting the data and, also requiring an API key for API clients. The documentation will also change as some of these won't apply anymore.

And, we are also moving from 41.242.2.154 to a different server. We just left this on because the app still communicates with this.

**Comment by aksalj** [comment]
Oh okay! :wink: But still, shouldn't there be a notice somewhere? I tried using the app, got a little curious, and was surprised to find my name, phone and ID number out in the open :angry:

**Comment by muaad** [comment]
Ya. Sorry about that. There would be a notice somewhere if we were actually doing it intentionally. I had not even noticed that. Rails generates a lot of things for simplicity but some things just slip under the radar. Thanks for bringing it to our attention. I have just cleared those user pages.

**Comment by anyangocynthia** [comment]
Salama are you still willing to work with us ?

**Comment by aksalj** [comment]
Sure! Will contribute as much as I can.

**Comment by anyangocynthia** [comment]
Will you be available for the meeting i set up?

On Fri, Feb 27, 2015 at 3:28 PM, Salama AB <notifications@github.com> wrote:

> Sure! Will contribute as much as I can.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anyangocynthia/nyumba_kumi/issues/1#issuecomment-76387334>
> .
>



-- 
Regards,
Cynthia Anyango
Founder @ Ujirani Company <http://goo.gl/EBSnoC>
twitter: anyango_cynthia

*Be happy :)*

**Comment by aksalj** [comment]
Unfortunately no.

**Comment by anyangocynthia** [comment]
Ok cool
